# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def shared_pods
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTBlob',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    'RCTImage',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTSettings',
    'RCTVibration',
    'RCTLinkingIOS',
    'RCTCameraRoll',
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # 3rd 
  #pod 'RNDeviceInfo'          , :path => '../node_modules/react-native-device-info'
  #pod 'RNSVG'                 , :path => '../node_modules/react-native-svg'
  #pod 'Interactable'          , :path => '../node_modules/react-native-interactable'
  #pod 'rn-fetch-blob'         , :path => '../node_modules/rn-fetch-blob'
  #pod 'RNGestureHandler'      , :path => '../node_modules/react-native-gesture-handler'
  #pod 'RNScreens'             , :path => '../node_modules/react-native-screens'
  #pod 'RNZipArchive'          , :path => '../node_modules/react-native-zip-archive'
  #pod 'react-native-spinkit'  , :path => '../node_modules/react-native-spinkit'
  #pod 'react-native-webview'   , :path => '../third-libs/react-native-webview'
end

target 'playground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for playground
  shared_pods

  target 'playgroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end